--
-- PostgreSQL database dump
--

\restrict gCs9FuTJCZ55abvW41xF0wwLefBQwodTjeVWdZhtnYUHgkOBl0SZVvP061GPhrl

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: dicas_investimento; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (3, 'LCI e LCA: isencao total de IR para pessoa fisica', 'Letras de Credito Imobiliario e do Agronegocio sao isentas de Imposto de Renda para pessoa fisica. Costumam render entre 90% e 95% do CDI bruto, o que equivale a mais de 100% liquido. Garantidas pelo FGC ate R$ 250.000.', 'Renda Fixa', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (5, 'Debentures incentivadas: renda fixa com premio de retorno', 'Debentures de empresas de infraestrutura (rodovias, energia, saneamento) sao isentas de IR para pessoa fisica. Rendem acima do CDI e financiam projetos essenciais para o pais. Risco maior que CDB mas com retorno atrativo e previsivel.', 'Renda Fixa', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (6, 'Previdencia Privada PGBL: beneficio fiscal imediato', 'O PGBL permite deduzir ate 12% da renda bruta anual na declaracao de IR no modelo completo. Para quem esta na aliquota de 27,5%, isso equivale a um retorno imediato de 27,5% sobre o valor aplicado. Resgate so apos longo prazo.', 'Previdência', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (7, 'ETFs de Acoes: diversificacao automatica com baixo custo', 'ETFs como BOVA11 (Ibovespa) e IVVB11 (S&P 500) permitem investir em dezenas de empresas com uma unica operacao. Taxas de administracao abaixo de 0,3% ao ano contra 2% a 3% dos fundos tradicionais. Ideal para iniciantes e avancados.', 'Ações', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (8, 'Acoes de dividendos: renda passiva em reais', 'Empresas consolidadas como bancos (BBAS3, ITUB4), elétricas (TAEE11, EGIE3) e saneamento (SAPR11) distribuem dividendos generosos. Analise o Dividend Yield historico, payout ratio e consistencia dos pagamentos antes de investir.', 'Ações', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (9, 'Buy and Hold: a filosofia dos grandes investidores', 'Comprar acoes de empresas excelentes e mante-las por decadas e a estrategia de Warren Buffett. O tempo e o maior aliado: juros compostos, reinvestimento de dividendos e crescimento dos lucros constroem patrimonio solido no longo prazo.', 'Ações', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (10, 'Como analisar acoes pelo P/L e P/VP', 'O P/L (Preco/Lucro) indica quantos anos levaria para recuperar o investimento. P/VP (Preco/Valor Patrimonial) mostra se a acao esta cara ou barata em relacao ao patrimonio. Combine com ROE, divida liquida e crescimento de lucros.', 'Ações', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (11, 'Small Caps: empresas menores com maior potencial de crescimento', 'Empresas de menor porte (fora do Ibovespa) crescem mais rapidamente e sao menos analisadas, criando oportunidades de compra abaixo do valor justo. Exige pesquisa aprofundada e maior tolerancia a volatilidade. Horizonte minimo: 5 anos.', 'Ações', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (12, 'Opcoes e protecao de carteira: hedge para investidores avancados', 'Opcoes de venda (puts) funcionam como um seguro para sua carteira de acoes. Em cenarios de queda, a put valoriza protegendo o patrimonio. Estrategias como protective put e collar sao usadas por gestores profissionais para limitar perdas.', 'Ações', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (13, 'FIIs de Tijolo vs FIIs de Papel: entenda a diferenca', 'FIIs de Tijolo investem em imoveis fisicos (shoppings, galpoes logisticos, lajes corporativas). FIIs de Papel investem em CRIs e CRAs. Em alta de juros, os de Papel se beneficiam. Em queda de juros, os de Tijolo tendem a valorizar mais.', 'FIIs', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (14, 'Galpoes logisticos: o segmento mais promissor dos FIIs', 'Com o boom do e-commerce, galpoes de alto padrao (Classe A+) proximos a grandes centros urbanos estao em altissima demanda. FIIs como BRCO11, LVBI11 e XPML11 sao referencia no setor. Contratos longos e inquilinos solidos garantem previsibilidade.', 'FIIs', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (15, 'Como avaliar um FII: P/VP, DY e vacancia', 'Um FII com P/VP abaixo de 1,0 pode indicar desconto sobre o valor real dos imoveis. O Dividend Yield mensal deve ser avaliado junto a qualidade dos contratos, vacancia fisica e financeira, solidez dos inquilinos e historico de distribuicoes.', 'FIIs', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (16, 'FIIs de Shopping: recuperacao pos-pandemia e dividendos crescentes', 'Shoppings dominantes em suas regioes como VISC11, XPML11 e HSML11 recuperaram o fluxo de visitantes e expandiram contratos. Receitas de estacionamento, quiosques e expansao de mix diversificam a renda alem do aluguel basico.', 'FIIs', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (17, 'FIIs de CRI: renda fixa com retorno de renda variavel', 'FIIs de papel como KNCR11 e MXRF11 investem em CRIs (Certificados de Recebiveis Imobiliarios) indexados ao CDI ou IPCA. Sao menos volateis que os de tijolo e distribuem rendimentos mensais previsíveis, isentos de IR para pessoa fisica.', 'FIIs', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (18, 'Diversificacao em FIIs: monte uma carteira equilibrada', 'Uma carteira de FIIs equilibrada combina diferentes segmentos: 30% logistica, 25% CRIs/papel, 20% shoppings, 15% lajes corporativas e 10% hibridos. Diversificar reduz o risco especifico de cada segmento e suaviza a distribuicao mensal.', 'FIIs', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (19, 'VGBL vs PGBL: qual e o certo para voce?', 'O PGBL e indicado para quem declara IR no modelo completo (deduz ate 12% da renda bruta). O VGBL e melhor para o modelo simplificado ou isento. No resgate, o IR incide sobre todo o saldo no PGBL e apenas sobre o rendimento no VGBL.', 'Previdência', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (20, 'Tabela regressiva na previdencia: quanto mais tempo, menos IR', 'A tabela regressiva parte de 35% (ate 2 anos) e chega a 10% (acima de 10 anos). Para horizontes longos, e quase sempre a melhor opcao comparada a tabela progressiva. Planeje saques parcelados para maximizar o beneficio tributario.', 'Previdência', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (21, 'Portabilidade de previdencia: como trocar sem pagar IR', 'E possivel migrar o saldo de uma previdencia para outra seguradora sem incidencia de IR e sem resgate. Use a portabilidade para fugir de fundos ruins, taxas abusivas ou gestoras que nao entregam resultado. O processo leva ate 10 dias uteis.', 'Previdência', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (4, 'Tesouro IPCA+: protecao real contra a inflacao', 'O Tesouro IPCA+ garante uma taxa de juros real acima da inflacao. Ideal para objetivos de longo prazo como aposentadoria ou compra de imovel. Atencao: quanto maior o prazo, maior a volatilidade no curto prazo por marcacao a mercado.', 'Renda Fixa', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 1);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (2, 'CDB com liquidez diaria: alternativa ao Tesouro Selic', 'Bancos digitais como Nubank, Inter e PicPay oferecem CDBs com liquidez diaria pagando 100% a 105% do CDI. Garantidos pelo FGC ate R$ 250.000 por CPF por instituicao. Excelente para quem quer rentabilidade sem abrir mao da liquidez.', 'Renda Fixa', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (22, 'Previdencia infantil: o maior presente para os filhos', 'Iniciar uma previdencia para filhos pequenos e uma das decisoes financeiras mais poderosas. Com 18 anos de contribuicao, o impacto dos juros compostos e enorme. Prefira fundos com taxa de administracao abaixo de 0,7% ao ano.', 'Previdência', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (23, 'Como escolher um bom fundo de previdencia', 'Avalie: taxa de administracao (ideal abaixo de 0,7% ao ano), taxa de carregamento (deve ser zero), historico de rentabilidade acima do CDI no longo prazo, qualidade da gestora e politica de investimentos alinhada ao seu perfil.', 'Previdência', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (24, 'Bitcoin: reserva de valor digital do seculo XXI', 'Com oferta maxima de 21 milhoes de unidades, o Bitcoin e deflacionario por natureza. O halving a cada 4 anos reduz a emissao de novos BTC, historicamente impulsionando o preco. Indicado como reserva de valor com alocacao entre 1% e 5% da carteira.', 'Criptomoedas', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (25, 'DCA em cripto: reduzindo o risco da volatilidade extrema', 'A estrategia Dollar Cost Averaging (comprar valor fixo periodicamente) reduz o impacto de comprar no pico do mercado. Em cripto, onde quedas de 50% a 80% sao historicas, o DCA melhora significativamente o preco medio de aquisicao ao longo do tempo.', 'Criptomoedas', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (26, 'Ethereum e o ecossistema DeFi', 'O Ethereum e a principal plataforma de contratos inteligentes, base para DeFi, NFTs e Web3. Apos a migracao para Proof of Stake (The Merge), o ETH se tornou deflacionario em periodos de alta atividade. Staking gera entre 3% e 5% ao ano.', 'Criptomoedas', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (27, 'Staking: renda passiva com suas criptomoedas', 'Blockchains Proof of Stake permitem travar tokens para validar transacoes e receber recompensas. Ethereum, Solana e Cardano oferecem rendimentos anuais entre 3% e 8%. Atencao: alem da volatilidade do ativo, ha riscos de protocolo e custoria.', 'Criptomoedas', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (28, 'Bitcoin ETF: acesso ao cripto sem abrir carteira digital', 'ETFs de Bitcoin aprovados pela SEC (EUA) como IBIT (BlackRock) e FBTC (Fidelity) permitem exposicao ao BTC atraves de corretoras tradicionais. No Brasil, ETFs como QBTC11 oferecem exposicao similar com custoria simplificada.', 'Criptomoedas', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (29, 'Seguranca em cripto: como nao perder seus ativos', 'A regra de ouro: "not your keys, not your coins". Carteiras de hardware (Ledger, Trezor) garantem que voce e o unico custodiante. Nunca compartilhe sua seed phrase. Para valores acima de R$ 5.000, prefira auto-custodia a deixar em exchanges.', 'Criptomoedas', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (30, 'ETFs do S&P 500: as 500 maiores empresas dos EUA', 'ETFs como IVVB11 (B3) ou VOO/IVV (NYSE) dao exposicao as 500 maiores empresas americanas. Historicamente o S&P 500 retorna cerca de 10% ao ano em dolares. Diversificacao cambial e geografica protegem contra riscos do mercado local.', 'Exterior', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (31, 'Como investir no exterior sem sair do Brasil', 'BDRs (Brazilian Depositary Receipts) permitem comprar fracoes de acoes estrangeiras pela B3. ETFs como IVVB11 e NASD11 dao exposicao a indices globais. Para valores maiores, plataformas como Avenue e Nomad facilitam investimento direto em dolares.', 'Exterior', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (32, 'REITs: os FIIs americanos com historico de 50 anos', 'Real Estate Investment Trusts sao obrigados por lei a distribuir 90% do lucro como dividendos. Realty Income (O), Simon Property (SPG) e Prologis (PLD) sao referencia em renda passiva em dolar com historico de pagamentos por decadas consecutivas.', 'Exterior', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (33, 'Diversificacao global: por que investir fora do Brasil?', 'O Brasil representa menos de 2% do PIB mundial. Investir no exterior reduz risco pais, protege contra desvalorizacao do real e da acesso a empresas como Apple, Microsoft e Amazon. Recomenda-se alocar de 15% a 30% do patrimonio no exterior.', 'Exterior', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (34, 'Acoes de crescimento nos EUA: Big Tech e alem', 'Empresas como NVIDIA, Apple, Microsoft e Amazon compoe o nucleo de portfolios de crescimento nos EUA. Analise P/L forward, crescimento de receita e margens. ETFs tematicos como QQQ (Nasdaq 100) oferecem exposicao diversificada ao setor de tecnologia.', 'Exterior', 'Alto', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (35, 'Declaracao de bens no exterior: o que a Receita exige', 'Brasileiros com bens ou investimentos no exterior acima de USD 1.000 devem declarar ao Banco Central (CBE anual). Na declaracao de IR, cada ativo e informado pelo custo de aquisicao em reais. Ganhos em moeda estrangeira sao tributados pelo GCAP.', 'Exterior', 'Médio', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (1, 'Tesouro Selic: liquidez diaria para reserva de emergencia', 'O Tesouro Selic e a escolha ideal para guardar sua reserva de emergencia. Acompanha a taxa Selic com liquidez diaria, risco praticamente zero e e garantido pelo governo federal. Rendimento atual proximo a 13,75% ao ano.', 'Renda Fixa', 'Baixo', 'Prof. Alexandre', '2026-06-15 15:36:04.673467-03', 0);
INSERT INTO public.dicas_investimento (id, titulo, descricao, categoria, risco, autor, data_criacao, votos) VALUES (36, 'Teste', 'Teste', 'Renda Fixa', 'Médio', 'Nathan', '2026-06-15 19:05:06.874742-03', 1);


--
-- Data for Name: comentarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (1, 1, 'João Silva', 'Excelente dica! Comecei minha reserva de emergencia assim.', '2026-06-15 15:36:04.673467-03');
INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (2, 1, 'Maria Oliveira', 'A taxa ta otima agora, mas sera que baixa logo?', '2026-06-15 15:36:04.673467-03');
INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (3, 7, 'Carlos Santos', 'Eu gosto muito do IVVB11 pra diversificar em dolar.', '2026-06-15 15:36:04.673467-03');
INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (4, 24, 'Ana Costa', 'Muito arriscado pra mim, prefiro ficar so na renda fixa por enquanto!', '2026-06-15 15:36:04.673467-03');
INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (5, 24, 'Pedro Souza', 'DCA e a melhor estrategia mesmo, nao da pra adivinhar o fundo.', '2026-06-15 15:36:04.673467-03');
INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (6, 7, 'Nathan', 'Muito legal
', '2026-06-15 15:36:43.414244-03');
INSERT INTO public.comentarios (id, dica_id, autor, texto, data_criacao) VALUES (8, 36, 'Nath', 'Nossa muito bom, te amo.', '2026-06-15 19:05:21.403833-03');


--
-- Name: comentarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comentarios_id_seq', 8, true);


--
-- Name: dicas_investimento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dicas_investimento_id_seq', 36, true);


--
-- PostgreSQL database dump complete
--

\unrestrict gCs9FuTJCZ55abvW41xF0wwLefBQwodTjeVWdZhtnYUHgkOBl0SZVvP061GPhrl

